# Generated by Django 3.2 on 2023-07-09 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_verificaioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificaioncode',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
