# Generated by Django 3.2 on 2023-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_verificaioncode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificaioncode',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
