# Generated by Django 3.2 on 2023-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_verificaioncode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificaioncode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
